### ISSUE TITLE
Daily Checklist 🕔

### ISSUE THREAD

**Issue by fluteds** [fluteds/acnh#2]
Resets at 🕔 **`5:00 am`**

* [ ] Check in at the Nook Stop (300 Nook Miles per day after your first 6 days)
* [ ] Shop the Nook Stop for new special catalog items and fence recipes
* [ ] Shop at Nook’s Cranny and the Able Sisters’
* [ ] Complete the first 5 Nook Miles+ missions of the day for 2x bonus
* [ ] Find your island’s 4 fossils
* [ ] Find your island’s DIY Recipe message in a bottle
* [ ] Find your island’s glowing money spot for 💰1,000 Bells. (Optional: Re-plant money in the spot to grow a “money tree" to multiply your investment!)
* [ ] Harvest resources
  * [ ] Rocks (materials — including up to 💰16,000 Bells from one rock)
  * [ ] Trees
    * [ ] Wood
    * [ ] Fruits (grow every three days after they were last picked)
    * [ ] Furniture, ~💰1,000 Bells, and/or wasps from cedar/hardwood trees
